name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_presets: https://raw.githubusercontent.com/lowlighter/metrics/presets/lunar-red/preset.yam
          config_output: insights
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          plugin_languages: yes
          plugin_languages_indepth: yes
          filename: metrics.plugin.lines.svg
          base: repositories
          plugin_lines: yes
          plugin_lines_delay: 30